version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: jobhouseDB
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./jobhouseDB:/var/lib/postgresql/data

